import { bus } from '/js/event-bus.js';
import { ExpressionSystem, PRESETS as EXPR_PRESETS } from '/js/expression-system.js';
import { GazeTracker } from '/js/gaze-tracker.js';
import { IntentFusionEngine } from '/js/intent-fusion.js';

export { bus, EXPR_PRESETS };
export const expressionSystem = new ExpressionSystem();
export const gazeTracker = new GazeTracker();
export const intentFusion = new IntentFusionEngine();

// Cross-module function registry — modules register their public functions
// here during init(), other modules call them via fn.functionName()
export const fn = {};

export const S = {
  serverUrl: localStorage.getItem('oc_server') || '',
  token: localStorage.getItem('oc_token') || '',
  messages: [],
  attachments: [],
  voiceWs: null,
  isRecording: false,
  isSending: false,
  isCameraOn: false,
  streamingMsgEl: null,
  streamingText: '',
  mediaStream: null,
  cameraStream: null,
  gestureRecognizer: null,
  faceLandmarker: null,
  drawingUtils: null,
  gestureAnimFrame: null,
  audioQueue: [],
  isPlayingAudio: false,
  continuousMode: false,
  appVolume: 1.0,
};

export const I18N = {
  zh: {
    'setup.title':'十三香小龙虾','setup.subtitle':'扫描二维码连接主机',
    'setup.qrInit':'正在初始化摄像头...','setup.or':'或者',
    'setup.urlPlaceholder':'服务器地址 (如 http://192.168.1.100:8765)',
    'setup.tokenPlaceholder':'令牌 (可选)','setup.connect':'连接',
    'setup.useCurrentServer':'使用当前服务器','setup.connecting':'连接中...',
    'setup.connectFailed':'连接失败，请检查地址。',
    'setup.pointCamera':'将摄像头对准二维码...',
    'setup.cameraUnavailable':'摄像头不可用，请手动输入地址。',
    'setup.qrDetected':'二维码已识别！正在连接...',
    'setup.invalidQr':'无效的二维码，请重试。',
    'header.title':'十三香小龙虾','header.desktop':'远程桌面',
    'header.camera':'摄像头','header.settings':'设置',
    'welcome.hello':'你好！','welcome.subtitle':'今天我能帮你做什么？',
    'welcome.s1':'你能做什么？','welcome.s2':'给我讲个笑话',
    'welcome.s3':'帮我写代码','welcome.s4':'给我解释一下',
    'input.placeholder':'输入消息...','input.attach':'添加附件','input.voice':'语音输入',
    'attach.toAI':'发给 AI','attach.toAIHint':'聊天/分析',
    'attach.toPc':'上传到电脑','attach.toPcHint':'保存到本地',
    'upload.uploading':'正在上传...','upload.done':'上传完成',
    'upload.saved':'已保存到: {path}','upload.failed':'上传失败: {err}',
    'upload.openFolder':'打开文件夹',
    'voice.listening':'正在聆听...','voice.processing':'处理中...',
    'voice.thinking':'思考中...','voice.speaking':'朗读中...',
    'voice.startingMic':'正在启动麦克风...',
    'voice.listeningHz':'正在聆听... ({rate}Hz)',
    'voice.connecting':'正在连接服务器...','voice.interrupted':'已打断，请说话',
    'wake.waitingCam':'等待摄像头就绪...',
    'vision.analyzing':'AI 正在分析画面...',
    'voice.silentMic':'麦克风无声，请检查权限或重试',
    'voice.noSpeech':'未检测到语音，请重试',
    'voice.micError':'麦克风错误: {msg}','voice.continuous':'连续模式',
    'voice.tapToEnd':'点击结束',
    'voice.stopSpeaking':'停止朗读',
    'camera.title':'摄像头和手势','camera.capture':'📸 拍照',
    'camera.requesting':'正在请求摄像头...',
    'camera.ok':'摄像头正常 ({size})',
    'camera.starting':'正在启动摄像头... ({count})',
    'camera.black':'摄像头黑屏 — 请在 iOS 设置中检查权限',
    'camera.deniedIOS':'🚫 摄像头权限被拒绝。前往 iOS 设置 → Safari → 摄像头 → 允许',
    'camera.deniedOther':'🚫 摄像头权限被拒绝。点击地址栏锁图标允许访问。',
    'camera.notFound':'📷 未找到摄像头设备。',
    'camera.blockedIOS':'🔒 摄像头被 iOS 拦截。需要安装并信任 CA 证书：<br><b>1.</b> 打开 <a href="/setup" style="color:var(--accent)">/setup</a> → 下载证书<br><b>2.</b> 设置 → 通用 → VPN与设备管理 → 安装<br><b>3.</b> 设置 → 通用 → 关于本机 → 证书信任设置 → 启用',
    'camera.needsHttps':'🔒 摄像头需要 HTTPS。请访问 <a href="/setup" style="color:var(--accent)">/setup</a> 查看说明。',
    'camera.error':'摄像头错误: {error}',
    'camera.loadingMP':'正在加载 MediaPipe...','camera.ready':'就绪',
    'camera.mpUnavailable':'MediaPipe 不可用','camera.noGestures':'无手势',
    'settings.title':'设置','settings.connection':'连接',
    'settings.server':'服务器','settings.status':'状态',
    'settings.hostIps':'主机 IP','settings.connected':'已连接',
    'settings.shareQr':'分享 (二维码)',
    'settings.shareDesc':'用其他设备扫描此二维码以连接',
    'settings.qrUnavailable':'二维码不可用',
    'settings.voice':'语音','settings.continuousMode':'连续模式',
    'settings.wakeWord':'语音唤醒 ("你好小龙")',
    'settings.gestureWake':'手势唤醒 (挥手)',
    'settings.display':'显示','settings.fullscreen':'全屏',
    'settings.enterFs':'进入全屏','settings.exitFs':'退出全屏',
    'settings.theme':'主题','settings.themeDark':'🌙 深色','settings.themeLight':'☀️ 浅色','settings.themeAuto':'🌗 自动',
    'settings.emotionAware':'情感感知','settings.emotionHint':'开启后 AI 会根据语音情绪自动调整回复语气和 TTS 风格',
    'settings.iosTip':'iOS 提示：在 Safari 中点击分享 → 添加到主屏幕，可实现永久全屏',
    'settings.disconnect':'断开连接','settings.back':'返回','settings.language':'语言',
    'model.title':'📦 模型管理','model.loading':'加载中…','model.installed':'✓ 已安装','model.install':'安装',
    'model.uninstall':'卸载','model.installing':'安装中…','model.cancelled':'已取消','model.failed':'安装失败',
    'model.verifying':'验证中…','model.verifyFail':'⚠️ 安装完成但验证失败，模块可能无法导入',
    'model.batchSelected':'已选 {n} 个模型','model.batchInstall':'批量安装','model.batchCancel':'取消',
    'model.queueProgress':'队列进度: {i}/{n} — 正在安装 {id}…','model.queueDone':'✓ 队列完成: {n} 个模型',
    'model.fullMode':'完整模式','model.minMode':'极简模式','model.noGpu':'无 GPU',
    'mcp.title':'🔌 MCP 工具','mcp.servers':'服务器','mcp.tools':'可用工具','mcp.toolHint':'— 点击工具可测试',
    'mcp.skills':'用户技能','mcp.noServers':'尚未注册 MCP 服务器','mcp.noTools':'连接服务器后将自动发现工具',
    'mcp.noSkills':'还没有自定义技能','mcp.addServer':'+ 添加 MCP 服务器','mcp.addServerBtn':'添加服务器',
    'mcp.addingServer':'添加中…','mcp.connect':'连接','mcp.connected':'已连接','mcp.disconnected':'未连接',
    'mcp.genSkill':'✨ 生成技能','mcp.generating':'生成中…','mcp.deleteSkill':'删除',
    'mcp.toolRun':'▶ 调用','mcp.toolRunning':'调用中…','mcp.toolClose':'关闭','mcp.rawJson':'原始 JSON',
    'mcp.noParams':'此工具无需参数','mcp.jsonError':'⚠️ JSON 参数格式错误',
    'mic.holdHint':'长按说话，松开结束',
    'toast.installOk':'模型 {id} 安装成功','toast.installFail':'模型 {id} 安装失败',
    'toast.verifyFail':'模型 {id} 验证失败，可能无法导入','toast.uninstallOk':'模型 {id} 已卸载',
    'toast.cancelled':'安装已取消','toast.batchDone':'批量安装完成: {n} 个模型',
    'shortcuts.title':'⌨️ 键盘快捷键','shortcuts.models':'模型管理','shortcuts.mcp':'MCP 工具',
    'shortcuts.theme':'切换主题','shortcuts.voice':'语音输入','shortcuts.escape':'关闭面板',
    'shortcuts.help':'此帮助','shortcuts.close':'关闭',
    'mcp.fav':'收藏','mcp.unfav':'取消收藏',
    'mcp.history':'调用历史','mcp.clearHistory':'清空','mcp.noHistory':'还没有调用记录','mcp.replay':'重放',
    'perf.title':'📊 性能监控','perf.wsLatency':'WebSocket 延迟','perf.sttTime':'STT 识别',
    'perf.aiTime':'AI 响应','perf.ttsTime':'TTS 首包','perf.timeline':'请求时间线 (最近 30 次)',
    'perf.session':'本次会话','perf.totalReqs':'总请求数','perf.avgLatency':'平均延迟',
    'vcmd.title':'🗣️ 语音指令','vcmd.searchPlaceholder':'搜索技能…','vcmd.execute':'执行','vcmd.noSkills':'暂无可用技能',
    'vcmd.customTitle':'🔗 自定义指令','vcmd.addCustom':'+ 新建','vcmd.save':'保存','vcmd.deleteConfirm':'确认删除此自定义指令？',
    'vcmd.customEmpty':'暂无自定义指令，点击新建创建组合指令','vcmd.namePlaceholder':'指令名称','vcmd.runningStep':'正在执行步骤',
    'shortcuts.perf':'性能监控','shortcuts.palette':'命令面板',
    'settings.dataTitle':'数据','settings.export':'📤 导出设置','settings.import':'📥 导入设置','settings.dataHint':'导出/导入主题、收藏、历史等本地设置',
    'settings.exportOk':'设置已导出','settings.importOk':'设置已导入，页面将刷新','settings.importFail':'导入失败：无效的设置文件',
    'cmd.placeholder':'输入命令…','cmd.empty':'无匹配结果','cmd.recent':'最近使用',
    'ws.excellent':'优秀','ws.good':'良好','ws.fair':'一般','ws.poor':'较差','ws.reconnecting':'重新连接中… {s}s','ws.degraded':'连接不稳定，部分功能可能受影响',
    'notif.title':'🔔 通知','notif.readAll':'全部已读','notif.clearAll':'清空','notif.empty':'暂无通知',
    'model.viewList':'📋 列表','model.viewDeps':'🔗 依赖关系','model.depTitle':'模型依赖关系','model.depMissing':'缺少前置依赖','model.depOk':'依赖已就绪',
    'model.bench':'⚡ 测试','model.benching':'测试中…','model.benchDone':'测试完成','model.benchFail':'测试失败',
    'model.benchSpeed':'推理速度','model.benchTTFT':'首 token','model.benchTokens':'token/s',
    'qa.screenshot':'截图','qa.translate':'翻译','qa.summarize':'总结','qa.wechat':'微信','qa.desktop':'桌面',
    'sess.title':'💬 会话','sess.new':'+ 新建','sess.empty':'暂无历史会话','sess.deleteConfirm':'确认删除此会话？','sess.current':'当前',
    'settings.wakewordPlaceholder':'自定义唤醒词（多个用逗号分隔）','settings.sensitivity':'灵敏度',
    'settings.sensitivityLow':'低','settings.sensitivityMed':'中','settings.sensitivityHigh':'高',
    'search.placeholder':'搜索消息…','search.count':'{x}/{y}','search.noResults':'无结果',
    'settings.qaEditor':'快捷操作','settings.qaNamePlaceholder':'名称','settings.qaSkillPlaceholder':'技能 ID','settings.qaAdd':'添加',
    'settings.qaPreset':'预设','settings.qaDeleteConfirm':'删除此快捷操作？',
    'bm.title':'⭐ 收藏','bm.empty':'暂无收藏消息','bm.remove':'取消收藏','bm.added':'已收藏','bm.removed':'已取消收藏',
    'settings.ttsPreview':'🔊 试听 TTS','settings.ttsPlaying':'⏹ 停止','settings.ttsPreviewing':'播放中…',
    'settings.vizMode':'音频可视化','settings.vizWave':'波形','settings.vizBars':'频谱条',
    'export.favOnly':'仅收藏消息','export.done':'导出完成','export.noData':'无消息可导出',
    'subtitle.listening':'正在聆听…',
    'sc.title':'🔗 技能链编辑器','sc.open':'🔗 技能链','sc.new':'+ 新建','sc.save':'💾 保存','sc.run':'▶ 运行','sc.delete':'🗑️',
    'sc.running':'运行中…','sc.done':'技能链执行完成','sc.saved':'已保存','sc.deleted':'已删除','sc.noNodes':'请先添加技能节点',
    'sc.dragHint':'从左侧拖入技能','sc.namePrompt':'技能链名称：',
    'sandbox.blocked':'插件请求被安全策略拒绝',
    'reactions.title':'表情回应',
    'translate.btn':'翻译','translate.loading':'翻译中…','translate.hide':'收起翻译','translate.error':'翻译失败',
    'keymap.title':'⌨️ 快捷键','keymap.searchPlaceholder':'搜索快捷键…',
    'keymap.general':'通用','keymap.voice':'语音','keymap.navigation':'导航','keymap.command':'命令','keymap.panels':'面板',
    'sc.templates':'📦 模板','sc.tplTitle':'技能链模板','sc.tplUse':'使用',
    'edit.resend':'重新发送','edit.cancel':'取消',
    'upload.dropHint':'释放以上传文件','upload.confirm':'发送','upload.cancel':'取消','upload.uploading':'上传中…','upload.done':'上传完成','upload.error':'上传失败',
    'summary.title':'📋 对话摘要','summary.generating':'正在生成摘要…','summary.noMsg':'暂无消息','summary.copied':'已复制到剪贴板','summary.collapse':'折叠','summary.expand':'展开',
    'pin.title':'📌 置顶消息','pin.max':'最多固定 3 条消息','pin.more':'展开更多','pin.unpin':'取消固定',
    'settings.plugins':'插件','settings.noPlugins':'暂无已注册插件','settings.pluginHint':'通过 window.ocPlugins.register() 注册插件',
    'settings.advTheme':'高级主题','settings.accentColor':'强调色','settings.fontSize':'字体大小','settings.resetTheme':'重置为默认',
    'desktop.title':'远程桌面','desktop.gestureCtrl':'手势控制',
    'desktop.ai.placeholder':'输入桌面指令（如：打开微信、给张三发消息）...',
    'desktop.ai.clicking':'正在点击','desktop.ai.typing':'正在输入',
    'desktop.ai.pressing':'正在按键','desktop.ai.executing':'正在执行',
    'desktop.ai.done':'执行完成',
    'desktop.touchHint':'点击操作 · 拖动移动 · 双指缩放滚动',
    'desktop.connecting':'已连接 — 等待画面...',
    'desktop.reconnecting':'正在重连...',
    'desktop.gestureOn':'手势控制已开启 · ☝️移动 · ✊单击/拖拽 · ✊✊双击 · ✌️右键 · 👍👎滚动 · ☝️✌️双指滚动 · ✋快滑=快捷键',
    'gesture.confirm':'确认','gesture.reject':'拒绝',
    'gesture.stop':'停止','gesture.desktop':'桌面',
    'gesture.voice':'语音','gesture.screenshot':'截图','gesture.hello':'你好',
    'gesture.confirmMsg':'好的，请继续',
    'gesture.rejectMsg':'不好，换一个方案',
    'gesture.helloMsg':'你好！有什么需要帮助的吗？',
    'gesture.openDesktopFirst':'请先打开远程桌面',
    'gesture.screenshotSaved':'截图已保存！',
    'gesture.voiceActivated':'语音已激活！',
    'gesture.gestureWake':'手势唤醒！',
    'gesture.pinch':'🤌 隔空截图','gesture.pinchSending':'📷 发给 AI 分析...',
    'gesture.vol':'🔊 音量 {pct}%',
    'combo.screenshotAI':'截图→AI分析','combo.langSwitch':'切换语言',
    'combo.desktopAgent':'桌面代理','combo.maxVol':'最大音量','combo.minVol':'静音',
    'combo.voiceCapture':'截图+语音',
    'snap.cmd1':'⏹ 停止朗读','snap.cmd2':'🎤 激活语音','snap.cmd3':'📷 截图分析',
    'snap.label':'响指 ×{n}',
    'face.smile':'😊 微笑','face.surprised':'😲 惊讶',
    'face.wink':'😉 眨眼','face.speaking':'😮 说话',
    'wake.label':'唤醒词："你好" / "小龙"',
    'wake.notSupported':'此浏览器不支持',
    'wake.starting':'正在启动唤醒...',
    'wake.say':'说："你好" / "小龙" / "Hey Claw"',
    'wake.heard':'听到了："{text}"','wake.matched':'唤醒："{text}"',
    'wake.restarting':'正在重启... ({error})',
    'wake.micNeeded':'需要麦克风权限',
    'wake.error':'错误: {error}','wake.startFailed':'启动失败: {msg}',
    'wake.paused':'唤醒已暂停','wake.listening':'正在监听 "你好" / "小龙"...',
    'fullscreen.toggle':'切换全屏',
    'file.tooLarge':'文件太大 (最大 20MB)',
    'error.prefix':'错误: {msg}',
    'systemPrompt':'你是 十三香小龙虾，一个有用、简洁、友好的助手。你可以帮助编程、写作、分析和回答一般问题。请用用户使用的语言回复。当被问到你自己时，说明你是 十三香小龙虾 助手。回复要简洁明了，适当使用 markdown 格式。',
    'profile.manage':'成员管理','profile.current':'当前成员','profile.quickAdd':'快速添加',
    'profile.family':'家庭模式','profile.work':'工作模式','profile.edit':'编辑成员',
    'profile.name':'名称','profile.env':'环境','profile.age':'年龄段','profile.voice':'语音',
    'profile.prompt':'系统提示词','profile.save':'保存','profile.cancel':'取消',
    'profile.switchOk':'已切换到「{name}」','profile.switchFail':'切换失败',
    'profile.deleteConfirm':'确定删除这个成员？其对话记忆将保留。',
    'profile.createOk':'已创建「{name}」','profile.updateOk':'「{name}」已更新',
    'profile.saveFail':'保存失败','profile.noMembers':'暂无成员，从下方模板快速创建',
    'clone.title':'语音克隆','clone.name':'声音名称','clone.record':'开始录音','clone.upload':'上传音频',
    'clone.stop':'停止录音','clone.processing':'处理中…','clone.list':'我的克隆声音',
    'clone.activate':'启用','clone.delete':'删除','clone.empty':'暂无克隆声音',
    'settings.tabGeneral':'通用','settings.tabVoice':'语音','settings.tabDisplay':'显示',
    'settings.tabData':'数据','settings.tabAdvanced':'高级',
    'onboard.step1':'开始对话','onboard.step1Desc':'在这里输入文字，或点击麦克风图标用语音对话',
    'onboard.step2':'个性设置','onboard.step2Desc':'点击齿轮进入设置，可切换主题、声音、AI 平台等',
    'onboard.step3':'更多功能','onboard.step3Desc':'点击这里查看摄像头、技能中心、模型管理等高级功能',
    'onboard.skip':'跳过','onboard.next':'下一步','onboard.done':'开始使用',
    'mode.simple':'简洁模式','mode.pro':'专业模式',
    'ui.expand':'展开全文','ui.collapse':'收起',
    'intent.title':'意图融合',
    'intent.badge_title':'意图融合状态',
    'intent.ch_gaze':'注视',
    'intent.ch_expr':'表情',
    'intent.ch_voice':'语音',
    'intent.ch_touch':'触控',
    'intent.ch_desktop':'桌面',
    'intent.fusion_none':'暂无融合结果',
    'intent.boosted':'跨模态增强',
    'intent.stats':'信号 / 融合 / 紧急',
    'intent.engine_on':'引擎运行中',
    'intent.engine_off':'引擎未运行',
    'intent.timeline':'500ms 窗口信号',
    'intent.emergency':'紧急停止',
    'intent.dev_tests':'开发 · 测试信号',
    'intent.test_nod':'点头',
    'intent.test_voice':'语音确认',
    'intent.test_touch':'触控点击',
  },
  en: {
    'setup.title':'十三香小龙虾','setup.subtitle':'Scan QR code to connect to your host',
    'setup.qrInit':'Initializing camera...','setup.or':'OR',
    'setup.urlPlaceholder':'Server URL (e.g. http://192.168.1.100:8765)',
    'setup.tokenPlaceholder':'Token (optional)','setup.connect':'Connect',
    'setup.useCurrentServer':'Use current server','setup.connecting':'Connecting...',
    'setup.connectFailed':'Connection failed. Check URL.',
    'setup.pointCamera':'Point camera at QR code...',
    'setup.cameraUnavailable':'Camera unavailable. Enter URL manually.',
    'setup.qrDetected':'QR detected! Connecting...',
    'setup.invalidQr':'Invalid QR code. Try again.',
    'header.title':'十三香小龙虾','header.desktop':'Remote Desktop',
    'header.camera':'Camera','header.settings':'Settings',
    'welcome.hello':'Hello!','welcome.subtitle':'How can I help you today?',
    'welcome.s1':'What can you do?','welcome.s2':'Tell me a joke',
    'welcome.s3':'Help me write code','welcome.s4':'Explain something',
    'input.placeholder':'Message 十三香小龙虾...','input.attach':'Attach file','input.voice':'Voice input',
    'attach.toAI':'Send to AI','attach.toAIHint':'Chat / Analyze',
    'attach.toPc':'Upload to PC','attach.toPcHint':'Save locally',
    'upload.uploading':'Uploading...','upload.done':'Upload Complete',
    'upload.saved':'Saved to: {path}','upload.failed':'Upload failed: {err}',
    'upload.openFolder':'Open Folder',
    'voice.listening':'Listening...','voice.processing':'Processing...',
    'voice.thinking':'Thinking...','voice.speaking':'Speaking...',
    'voice.startingMic':'Starting mic...',
    'voice.listeningHz':'Listening... ({rate}Hz)',
    'voice.connecting':'Connecting to server...','voice.interrupted':'Interrupted, speak now',
    'wake.waitingCam':'Waiting for camera...',
    'vision.analyzing':'AI analyzing frame...',
    'voice.silentMic':'Mic silent — check permission or try again',
    'voice.noSpeech':'No speech detected, try again',
    'voice.micError':'Mic error: {msg}','voice.continuous':'Continuous mode',
    'voice.tapToEnd':'Tap to end',
    'voice.stopSpeaking':'Stop speaking',
    'camera.title':'Camera & Gesture','camera.capture':'📸 Capture Photo',
    'camera.requesting':'Requesting camera...',
    'camera.ok':'Camera OK ({size})',
    'camera.starting':'Starting camera... ({count})',
    'camera.black':'Camera stream black — check permissions in iOS Settings',
    'camera.deniedIOS':'🚫 Camera permission denied. Go to iOS Settings → Safari → Camera → Allow',
    'camera.deniedOther':'🚫 Camera permission denied. Click the lock icon in the address bar to allow.',
    'camera.notFound':'📷 No camera found on this device.',
    'camera.blockedIOS':'🔒 Camera blocked by iOS. You need to install & trust the CA certificate:<br><b>1.</b> Open <a href="/setup" style="color:var(--accent)">/setup</a> → Download cert<br><b>2.</b> Settings → General → VPN & Device Mgmt → Install<br><b>3.</b> Settings → General → About → Certificate Trust → Enable',
    'camera.needsHttps':'🔒 Camera requires HTTPS. Visit <a href="/setup" style="color:var(--accent)">/setup</a> for instructions.',
    'camera.error':'Camera error: {error}',
    'camera.loadingMP':'Loading MediaPipe...','camera.ready':'Ready',
    'camera.mpUnavailable':'MediaPipe unavailable','camera.noGestures':'No gestures',
    'settings.title':'Settings','settings.connection':'Connection',
    'settings.server':'Server','settings.status':'Status',
    'settings.hostIps':'Host IPs','settings.connected':'Connected',
    'settings.shareQr':'Share (QR Code)',
    'settings.shareDesc':'Scan this QR from another device to connect',
    'settings.qrUnavailable':'QR unavailable',
    'settings.voice':'Voice','settings.continuousMode':'Continuous mode',
    'settings.wakeWord':'Voice wake-up ("Hey Claw")',
    'settings.gestureWake':'Gesture wake-up (wave hand)',
    'settings.display':'Display','settings.fullscreen':'Fullscreen',
    'settings.enterFs':'Enter Fullscreen','settings.exitFs':'Exit Fullscreen',
    'settings.theme':'Theme','settings.themeDark':'🌙 Dark','settings.themeLight':'☀️ Light','settings.themeAuto':'🌗 Auto',
    'settings.emotionAware':'Emotion Awareness','settings.emotionHint':'When enabled, AI adapts tone and TTS style based on voice emotion',
    'settings.iosTip':'iOS tip: In Safari tap Share → Add to Home Screen for permanent fullscreen',
    'settings.disconnect':'Disconnect','settings.back':'Back','settings.language':'Language',
    'model.title':'📦 Model Manager','model.loading':'Loading…','model.installed':'✓ Installed','model.install':'Install',
    'model.uninstall':'Uninstall','model.installing':'Installing…','model.cancelled':'Cancelled','model.failed':'Install failed',
    'model.verifying':'Verifying…','model.verifyFail':'⚠️ Installed but verification failed — module may not import',
    'model.batchSelected':'{n} models selected','model.batchInstall':'Batch Install','model.batchCancel':'Cancel',
    'model.queueProgress':'Queue: {i}/{n} — installing {id}…','model.queueDone':'✓ Queue done: {n} models',
    'model.fullMode':'Full mode','model.minMode':'Minimal mode','model.noGpu':'No GPU',
    'mcp.title':'🔌 MCP Tools','mcp.servers':'Servers','mcp.tools':'Available Tools','mcp.toolHint':'— click to test',
    'mcp.skills':'User Skills','mcp.noServers':'No MCP servers registered','mcp.noTools':'Connect a server to discover tools',
    'mcp.noSkills':'No custom skills yet','mcp.addServer':'+ Add MCP Server','mcp.addServerBtn':'Add Server',
    'mcp.addingServer':'Adding…','mcp.connect':'Connect','mcp.connected':'Connected','mcp.disconnected':'Disconnected',
    'mcp.genSkill':'✨ Generate Skill','mcp.generating':'Generating…','mcp.deleteSkill':'Delete',
    'mcp.toolRun':'▶ Call','mcp.toolRunning':'Calling…','mcp.toolClose':'Close','mcp.rawJson':'Raw JSON',
    'mcp.noParams':'No parameters needed','mcp.jsonError':'⚠️ Invalid JSON parameters',
    'mic.holdHint':'Hold to talk, release to send',
    'toast.installOk':'Model {id} installed','toast.installFail':'Model {id} install failed',
    'toast.verifyFail':'Model {id} verify failed — may not import','toast.uninstallOk':'Model {id} uninstalled',
    'toast.cancelled':'Installation cancelled','toast.batchDone':'Batch complete: {n} models',
    'shortcuts.title':'⌨️ Keyboard Shortcuts','shortcuts.models':'Model Manager','shortcuts.mcp':'MCP Tools',
    'shortcuts.theme':'Toggle Theme','shortcuts.voice':'Voice Input','shortcuts.escape':'Close Panel',
    'shortcuts.help':'This Help','shortcuts.close':'Close',
    'mcp.fav':'Favorite','mcp.unfav':'Unfavorite',
    'mcp.history':'Call History','mcp.clearHistory':'Clear','mcp.noHistory':'No call records yet','mcp.replay':'Replay',
    'perf.title':'📊 Performance','perf.wsLatency':'WebSocket Latency','perf.sttTime':'STT Time',
    'perf.aiTime':'AI Response','perf.ttsTime':'TTS First Byte','perf.timeline':'Request Timeline (last 30)',
    'perf.session':'This Session','perf.totalReqs':'Total Requests','perf.avgLatency':'Avg Latency',
    'vcmd.title':'🗣️ Voice Commands','vcmd.searchPlaceholder':'Search skills…','vcmd.execute':'Execute','vcmd.noSkills':'No skills available',
    'vcmd.customTitle':'🔗 Custom Commands','vcmd.addCustom':'+ New','vcmd.save':'Save','vcmd.deleteConfirm':'Delete this custom command?',
    'vcmd.customEmpty':'No custom commands yet, create one to combine skills','vcmd.namePlaceholder':'Command name','vcmd.runningStep':'Running step',
    'shortcuts.palette':'Command Palette',
    'settings.dataTitle':'Data','settings.export':'📤 Export Settings','settings.import':'📥 Import Settings','settings.dataHint':'Export/import theme, favorites, history and other local settings',
    'settings.exportOk':'Settings exported','settings.importOk':'Settings imported, page will reload','settings.importFail':'Import failed: invalid settings file',
    'cmd.placeholder':'Type a command…','cmd.empty':'No matches','cmd.recent':'Recently used',
    'ws.excellent':'Excellent','ws.good':'Good','ws.fair':'Fair','ws.poor':'Poor','ws.reconnecting':'Reconnecting… {s}s','ws.degraded':'Unstable connection, some features may be affected',
    'notif.title':'🔔 Notifications','notif.readAll':'Mark all read','notif.clearAll':'Clear all','notif.empty':'No notifications',
    'model.viewList':'📋 List','model.viewDeps':'🔗 Dependencies','model.depTitle':'Model Dependencies','model.depMissing':'Missing prerequisites','model.depOk':'Dependencies ready',
    'model.bench':'⚡ Bench','model.benching':'Testing…','model.benchDone':'Benchmark done','model.benchFail':'Benchmark failed',
    'model.benchSpeed':'Speed','model.benchTTFT':'TTFT','model.benchTokens':'token/s',
    'qa.screenshot':'Screenshot','qa.translate':'Translate','qa.summarize':'Summarize','qa.wechat':'WeChat','qa.desktop':'Desktop',
    'sess.title':'💬 Sessions','sess.new':'+ New','sess.empty':'No sessions yet','sess.deleteConfirm':'Delete this session?','sess.current':'Current',
    'settings.wakewordPlaceholder':'Custom wake words (comma separated)','settings.sensitivity':'Sensitivity',
    'settings.sensitivityLow':'Low','settings.sensitivityMed':'Mid','settings.sensitivityHigh':'High',
    'search.placeholder':'Search messages…','search.count':'{x}/{y}','search.noResults':'No results',
    'settings.qaEditor':'Quick Actions','settings.qaNamePlaceholder':'Name','settings.qaSkillPlaceholder':'Skill ID','settings.qaAdd':'Add',
    'settings.qaPreset':'Preset','settings.qaDeleteConfirm':'Delete this quick action?',
    'bm.title':'⭐ Bookmarks','bm.empty':'No bookmarked messages','bm.remove':'Remove','bm.added':'Bookmarked','bm.removed':'Bookmark removed',
    'settings.ttsPreview':'🔊 Preview TTS','settings.ttsPlaying':'⏹ Stop','settings.ttsPreviewing':'Playing…',
    'settings.vizMode':'Audio Visualization','settings.vizWave':'Waveform','settings.vizBars':'Frequency Bars',
    'export.favOnly':'Bookmarked only','export.done':'Export complete','export.noData':'No messages to export',
    'subtitle.listening':'Listening…',
    'sc.title':'🔗 Skill Chain Editor','sc.open':'🔗 Chains','sc.new':'+ New','sc.save':'💾 Save','sc.run':'▶ Run','sc.delete':'🗑️',
    'sc.running':'Running…','sc.done':'Skill chain complete','sc.saved':'Saved','sc.deleted':'Deleted','sc.noNodes':'Add skill nodes first',
    'sc.dragHint':'Drag skills from the left','sc.namePrompt':'Chain name:',
    'sandbox.blocked':'Plugin request blocked by security policy',
    'reactions.title':'Reactions',
    'translate.btn':'Translate','translate.loading':'Translating…','translate.hide':'Hide translation','translate.error':'Translation failed',
    'keymap.title':'⌨️ Shortcuts','keymap.searchPlaceholder':'Search shortcuts…',
    'keymap.general':'General','keymap.voice':'Voice','keymap.navigation':'Navigation','keymap.command':'Command','keymap.panels':'Panels',
    'sc.templates':'📦 Templates','sc.tplTitle':'Skill Chain Templates','sc.tplUse':'Use',
    'edit.resend':'Resend','edit.cancel':'Cancel',
    'upload.dropHint':'Drop to upload files','upload.confirm':'Send','upload.cancel':'Cancel','upload.uploading':'Uploading…','upload.done':'Upload complete','upload.error':'Upload failed',
    'summary.title':'📋 Chat Summary','summary.generating':'Generating summary…','summary.noMsg':'No messages','summary.copied':'Copied to clipboard','summary.collapse':'Collapse','summary.expand':'Expand',
    'pin.title':'📌 Pinned','pin.max':'Max 3 pinned messages','pin.more':'Show more','pin.unpin':'Unpin',
    'settings.plugins':'Plugins','settings.noPlugins':'No registered plugins','settings.pluginHint':'Register via window.ocPlugins.register()',
    'settings.advTheme':'Advanced Theme','settings.accentColor':'Accent Color','settings.fontSize':'Font Size','settings.resetTheme':'Reset to Default',
    'shortcuts.perf':'Performance',
    'desktop.title':'Remote Desktop','desktop.gestureCtrl':'Gesture control',
    'desktop.ai.placeholder':'Type desktop command (e.g. open WeChat, send message)...',
    'desktop.ai.clicking':'Clicking','desktop.ai.typing':'Typing',
    'desktop.ai.pressing':'Pressing','desktop.ai.executing':'Executing',
    'desktop.ai.done':'Done',
    'desktop.touchHint':'Tap to click · Drag to move · Pinch to scroll',
    'desktop.connecting':'Connected — waiting for frames...',
    'desktop.reconnecting':'Reconnecting...',
    'desktop.gestureOn':'Gesture ON · ☝️Move · ✊Click/Drag · ✊✊DblClick · ✌️RightClick · 👍👎Scroll · ☝️✌️2-finger · ✋Swipe=Shortcut',
    'gesture.confirm':'Confirm','gesture.reject':'Reject',
    'gesture.stop':'Stop','gesture.desktop':'Desktop',
    'gesture.voice':'Voice','gesture.screenshot':'Screenshot','gesture.hello':'Hello',
    'gesture.confirmMsg':'Yes, please continue',
    'gesture.rejectMsg':'No, give me another option',
    'gesture.helloMsg':'Hello! What can I help you with?',
    'gesture.openDesktopFirst':'Open Desktop first',
    'gesture.screenshotSaved':'Screenshot saved!',
    'gesture.voiceActivated':'Voice Activated!',
    'gesture.gestureWake':'Gesture Wake!',
    'gesture.pinch':'🤌 Aerial Screenshot','gesture.pinchSending':'📷 Sending to AI...',
    'gesture.vol':'🔊 Volume {pct}%',
    'combo.screenshotAI':'Screenshot→AI','combo.langSwitch':'Switch Language',
    'combo.desktopAgent':'Desktop Agent','combo.maxVol':'Max Volume','combo.minVol':'Mute',
    'combo.voiceCapture':'Screenshot+Voice',
    'snap.cmd1':'⏹ Stop Speaking','snap.cmd2':'🎤 Voice On','snap.cmd3':'📷 Capture AI',
    'snap.label':'Snap ×{n}',
    'face.smile':'😊 Smile','face.surprised':'😲 Surprised',
    'face.wink':'😉 Wink','face.speaking':'😮 Speaking',
    'wake.label':'Wake word: "Hey Claw"',
    'wake.notSupported':'Not supported in this browser',
    'wake.starting':'Starting wake word...',
    'wake.say':'Say: "你好" / "小龙" / "Hey Claw"',
    'wake.heard':'Heard: "{text}"','wake.matched':'Wake: "{text}"',
    'wake.restarting':'Restarting... ({error})',
    'wake.micNeeded':'Mic permission needed',
    'wake.error':'Error: {error}','wake.startFailed':'Start failed: {msg}',
    'wake.paused':'Wake word paused','wake.listening':'Listening for "Hey Claw" / "你好"...',
    'fullscreen.toggle':'Toggle fullscreen',
    'file.tooLarge':'File too large (max 20MB)',
    'error.prefix':'Error: {msg}',
    'systemPrompt':'You are 十三香小龙虾, a helpful, concise, and friendly assistant. You can help with coding, writing, analysis, and general questions. Respond in the user\'s language. When asked about yourself, explain you are 十三香小龙虾 assistant. Keep responses focused and well-formatted using markdown when appropriate.',
    'profile.manage':'Members','profile.current':'Current Members','profile.quickAdd':'Quick Add',
    'profile.family':'Family Mode','profile.work':'Work Mode','profile.edit':'Edit Member',
    'profile.name':'Name','profile.env':'Environment','profile.age':'Age Group','profile.voice':'Voice',
    'profile.prompt':'System Prompt','profile.save':'Save','profile.cancel':'Cancel',
    'profile.switchOk':'Switched to "{name}"','profile.switchFail':'Switch failed',
    'profile.deleteConfirm':'Delete this member? Chat history will be preserved.',
    'profile.createOk':'Created "{name}"','profile.updateOk':'"{name}" updated',
    'profile.saveFail':'Save failed','profile.noMembers':'No members yet. Create from templates below.',
    'clone.title':'Voice Clone','clone.name':'Voice Name','clone.record':'Start Recording','clone.upload':'Upload Audio',
    'clone.stop':'Stop Recording','clone.processing':'Processing…','clone.list':'My Cloned Voices',
    'clone.activate':'Activate','clone.delete':'Delete','clone.empty':'No cloned voices yet',
    'settings.tabGeneral':'General','settings.tabVoice':'Voice','settings.tabDisplay':'Display',
    'settings.tabData':'Data','settings.tabAdvanced':'Advanced',
    'onboard.step1':'Start Chatting','onboard.step1Desc':'Type a message here, or tap the mic icon to use voice',
    'onboard.step2':'Personalize','onboard.step2Desc':'Tap the gear icon to access settings: theme, voice, AI platform, etc.',
    'onboard.step3':'More Features','onboard.step3Desc':'Tap here for camera, skill center, model management and more',
    'onboard.skip':'Skip','onboard.next':'Next','onboard.done':'Get Started',
    'mode.simple':'Simple','mode.pro':'Pro',
    'ui.expand':'Show more','ui.collapse':'Show less',
    'intent.title':'Intent fusion',
    'intent.badge_title':'Intent fusion',
    'intent.ch_gaze':'Gaze',
    'intent.ch_expr':'Expression',
    'intent.ch_voice':'Voice',
    'intent.ch_touch':'Touch',
    'intent.ch_desktop':'Desktop',
    'intent.fusion_none':'No fused intent yet',
    'intent.boosted':'Boosted',
    'intent.stats':'Signals / Fusions / Emergency',
    'intent.engine_on':'Engine running',
    'intent.engine_off':'Engine off',
    'intent.timeline':'500ms window',
    'intent.emergency':'Emergency stop',
    'intent.dev_tests':'Dev · test signals',
    'intent.test_nod':'Nod',
    'intent.test_voice':'Voice confirm',
    'intent.test_touch':'Touch tap',
  }
};

export let currentLang = localStorage.getItem('oc-lang') || localStorage.getItem('oc_lang') || 'zh';

export function t(key, vars) {
  let text = I18N[currentLang]?.[key] || I18N['en']?.[key] || key;
  if (vars) {
    for (const [k, v] of Object.entries(vars)) {
      text = text.replace(`{${k}}`, v);
    }
  }
  return text;
}

export function applyLang() {
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    const attr = el.getAttribute('data-i18n-attr');
    if (attr === 'placeholder') el.placeholder = t(key);
    else if (attr === 'title') el.title = t(key);
    else el.textContent = t(key);
  });
  document.querySelectorAll('.suggestion[data-i18n-msg]').forEach(el => {
    el.textContent = t(el.getAttribute('data-i18n'));
    el.dataset.msg = t(el.getAttribute('data-i18n-msg'));
  });
}

export function mergeI18nBundles(zhPatch, enPatch) {
  if (zhPatch && typeof zhPatch === 'object') Object.assign(I18N.zh, zhPatch);
  if (enPatch && typeof enPatch === 'object') Object.assign(I18N.en, enPatch);
  applyLang();
}

export function setLang(lang) {
  currentLang = lang;
  localStorage.setItem('oc-lang', lang);
  localStorage.setItem('oc_lang', lang);
  S.SYSTEM_PROMPT = t('systemPrompt');
  applyLang();
  if (fn.rebuildGestureCommands) fn.rebuildGestureCommands();
}

S.SYSTEM_PROMPT = t('systemPrompt');

export const $ = (sel) => document.querySelector(sel);
export const $$ = (sel) => document.querySelectorAll(sel);

export const dom = {
  setupPage: $('#setup-page'),
  chatPage: $('#chat-page'),
  qrVideo: $('#qr-video'),
  qrCanvas: $('#qr-canvas'),
  qrStatus: $('#qr-status'),
  serverUrl: $('#server-url'),
  serverToken: $('#server-token'),
  connectBtn: $('#connect-btn'),
  skipBtn: $('#skip-setup-btn'),
  statusDot: $('#status-dot'),
  messagesArea: $('#messages-area'),
  messages: $('#messages'),
  welcome: $('#welcome-screen'),
  msgInput: $('#msg-input'),
  sendBtn: $('#send-btn'),
  attachBtn: $('#attach-btn'),
  micBtn: $('#mic-btn'),
  fileInput: $('#file-input'),
  previewBar: $('#preview-bar'),
  voiceOverlay: $('#voice-overlay'),
  voiceStatus: $('#voice-status'),
  voiceTranscript: $('#voice-transcript'),
  voiceBar: $('#voice-bar'),
  vbarStatus: $('#vbar-status'),
  vbarTranscript: $('#vbar-transcript'),
  voiceStop: $('#voice-stop'),
  voiceLevel: $('#voice-level'),
  cameraPanel: $('#camera-panel'),
  cameraVideo: $('#camera-video'),
  gestureCanvas: $('#gesture-canvas'),
  gestureTags: $('#gesture-tags'),
  captureBtn: $('#capture-btn'),
  cameraToggle: $('#camera-toggle'),
  cameraClose: $('#camera-close'),
  settingsModal: $('#settings-modal'),
  settingsToggle: $('#settings-toggle'),
  settingsClose: $('#settings-close'),
  infoServer: $('#info-server'),
  infoStatus: $('#info-status'),
  infoIps: $('#info-ips'),
  qrDisplay: $('#qr-display'),
  disconnectBtn: $('#disconnect-btn'),
  continuousMode: $('#continuous-mode'),
  toggleKnob: $('#toggle-knob'),
  lightbox: $('#lightbox'),
  lightboxImg: $('#lightbox-img'),
};

export function getBaseUrl() {
  return S.serverUrl || window.location.origin;
}

export function escapeHtml(text) {
  return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

export function init() {
  applyLang();
}
